version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: socialMedia-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: social_media
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./DB:/docker-entrypoint-initdb.d 
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network: